### ISSUE TITLE
Strange behaviour when navigating back between Cards

### ISSUE THREAD

**Issue by n1ru4l** [LeoLeBras/react-router-navigation#12]
This is my code
```jsx
    <Navigation navBarStyle={{ backgroundColor: 'purple' }} titleStyle={{ color: 'white' }}>
      <Card exact path="/watch" component={SeriesOverview} />
      <Card exact path="/watch/series/:seriesId" component={SeriesDetail} />
    </Navigation>
```

It seems that if you navigate back from SeriesDetail to SeriesOverview, the Component is rerendered without the match and history object. I wanted to ask why it behaves like that?

**Comment by LeoLeBras** [comment]
Hey @n1ru4l,
Strange behavior 😟 . Are you facing the same issue on this [example](https://github.com/LeoLeBras/react-router-navigation/tree/master/examples/Huge) ?

**Comment by n1ru4l** [comment]
When I comment out the `shouldComponentUpdate` method in `src/app/modules/Feed/components/Article/index.js` and add console.log( this.props.match ) to the render method I can reproduce this issue.

Also I noticed that there are many dispatches when using the BottomBarTabs the redux store logs the current route name 8 times ( and the buttom also flickers 8 times), which does not seem wanted to me :/

**Comment by chuyik** [comment]
Hi @LeoLeBras,
I found out if I clicked "See item X" button, then clicked "Feed" button on BottomNavigation, it can't be navigated back to the list, instead it just can't click anything.

**Comment by LeoLeBras** [comment]
@n1ru4l 
When you navigate back from ```/app/feed/article/:id``` to ```/app/feed```, the urls changes so ```match``` becomes ```null``` during the transition. You can use [```staticMatch```](https://github.com/LeoLeBras/react-router-navigation/blob/master/modules/Card.js#L25-L31) to fix this issue :
```
<Card
  ...
  render={({ match, staticMatch }) => (
    <Text>{match ? match.url : staticMatch.url}</Text>
  )}
</Card>
```



I refactored ```<BottomNavigation />``` and added a new ```<TabBarBottom />``` to fix many bugs. It reduces number of redux logs, fixes flicker effect ...
 Let me know if this solves your issue !

@chuyik 
Thanks for your feedback. This should be fixed in ```1.0.0-beta.3``` (https://github.com/LeoLeBras/react-router-navigation/commit/4eccc23e0fe0556c9bdfab6b7013d8798994bc21).

**Comment by n1ru4l** [comment]
@n1ru4l I will checkout staticMatch in a few minutes. I checked the performance of the Huge sample app and noticed that you have to change the dependency if `react-router-navigation` from to `file:./../../` to `v1.0.0-beta.3`, otherwise I would get lots of `@providesModule naming collision` errors when running `yarn install`. Switching on the BottomNavigation seems much better now, however the Tabs animations are laggy (I am using android and atm I am unable to test on ios). I recorded a short screencast - I will tyr to figure out how I can attach it here :D

**Comment by CharlesMangwa** [comment]
Hey @LeoLeBras: was this specific bug fixed in ß3 ?

@n1ru4l 
Thanks for your time, appreciate the feedback! Did you try the last beta and still needed `staticMatch`?

About your screencast: if I'm not mistaken, you were in `__DEV__ = true` mode there. Try to turn it off and see if you notice any changes.

**Comment by LeoLeBras** [comment]
@CharlesMangwa Yes !!
