### ISSUE TITLE
Support for React-Navigations Modal

### ISSUE THREAD

**Issue by ma-pe** [LeoLeBras/react-router-navigation#45]
Do you plan to support Modal-Views, as react-navigation provides?

At the moment the only solution seems to be using a new Navigator with custom transition while hiding the NavBar.

Greetings

**Comment by Rusfighter** [comment]
Isn't there any work around for this issue? Since i actually also require this kind of modals. 

The workaround i am looking for is that you have a top Navigation component. The cards are the "modals". Something like this:

```
<NativeRouter initialEntries={initialEntries}>
    <Navigation hideNavBar>
      <Card exact path="/launch" component={Launch} />
      <Card exact path="/auth" component={Auth} />
      <Card exact path="/app" component={App} />
      <Card exact path="/channel" component={Channel} />
    </Navigation>
  </NativeRouter>
```
Lets assume /app card is a BottomNavigation component with its tabs.

The problem now is that if I go from a tabView in the BottomNavigation to "modal card", eg path="/channel", it is impossible to go from /channel modal back to BottomNavigation tabView. 

I don't know if this is my fault or the idea is just impossible to achieve?

Ilija

**Comment by ma-pe** [comment]
I guess this may be closed in favor of merged pullrequest: https://github.com/LeoLeBras/react-router-navigation/pull/63
